In [1]:
import pandas as pd

df = pd.read_csv('/Users/thomascurl/Downloads/prepped_churn_data.csv', index_col='customerID')
df

,tenure,PhoneService,Contract,MonthlyCharges,TotalCharges,Churn,Tenure_TotalCharges_ratio,TotalCharges_Tenure_ratio
customerID,,,,,,,,
7590-VHVEG,1,0,1,29.85,29.85,0,0.033501,29.850000
5575-GNVDE,34,1,12,56.95,1889.50,0,0.017994,55.573529
3668-QPYBK,2,1,1,53.85,108.15,1,0.018493,54.075000
7795-CFOCW,45,0,12,42.30,1840.75,0,0.024447,40.905556
9237-HQITU,2,1,1,70.70,151.65,1,0.013188,75.825000
...,...,...,...,...,...,...,...,...
6840-RESVB,24,1,12,84.80,1990.50,0,0.012057,82.937500
2234-XADUH,72,1,12,103.20,7362.90,0,0.009779,102.262500
4801-JZAZL,11,0,1,29.60,346.45,0,0.031751,31.495455
8361-LTMKD,4,1,1,74.40,306.60,1,0.013046,76.650000
3186-AJIEK,66,1,24,105.65,6844.50,0,0.009643,103.704545

In [2]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [3]:
automl = setup(data = df, target = 'Churn',  fold_shuffle=True, imputation_type='iterative')

In [4]:
automl[6]

6071

In [5]:
automl[14]

In [6]:
best_model = compare_models()

In [7]:
best_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6071, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
df.iloc[-2:-1].shape

(1, 8)

In [9]:
predict_model(best_model, df.iloc[-2:-1])

,tenure,PhoneService,Contract,MonthlyCharges,TotalCharges,Churn,Tenure_TotalCharges_ratio,TotalCharges_Tenure_ratio,Label,Score
customerID,,,,,,,,,,
8361-LTMKD,4,1,1,74.4,306.6,1,0.013046,76.65,1,0.5797

In [10]:
df.iloc[-2:-1].shape

(1, 8)

In [11]:
save_model(best_model, 'LR')

Transformation Pipeline and Model Succesfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='Churn',
                                       time_features=[])),
                 ('imputer',
                  Iterative_Imputer(add_indicator=False,
                                    classifier=LGBMClassifier(boosting_type='gbdt',
                                                              class_weight=None,
                                                              colsample_bytree=...
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=6071,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False)]],
          verbose=False),
 'LDA.pkl')

In [15]:
new_data = df.iloc[-2:-1].copy()
new_data.drop('Churn', axis=1, inplace=True)
loaded_model.predict(df)

array([0, 1, 1, ..., 1, 1, 1])

In [17]:
new_data = df.iloc[-2:-1].copy()
new_data.drop('Churn', axis=1, inplace=True)
loaded_model.predict(new_data)

ValueError: X has 7 features per sample; expecting 8

In [18]:
automl[8]

False

In [19]:
automl[7]

{'acc': <pycaret.containers.metrics.classification.AccuracyMetricContainer at 0x7ffe3a4a3b80>,
 'auc': <pycaret.containers.metrics.classification.ROCAUCMetricContainer at 0x7ffe3a4a3970>,
 'recall': <pycaret.containers.metrics.classification.RecallMetricContainer at 0x7ffe3a4a3a60>,
 'precision': <pycaret.containers.metrics.classification.PrecisionMetricContainer at 0x7ffe3a4a39d0>,
 'f1': <pycaret.containers.metrics.classification.F1MetricContainer at 0x7ffe39247d00>,
 'kappa': <pycaret.containers.metrics.classification.KappaMetricContainer at 0x7ffe39247e50>,
 'mcc': <pycaret.containers.metrics.classification.MCCMetricContainer at 0x7ffe39247ee0>}

In [20]:
save_model(best_model, 'LR')

Transformation Pipeline and Model Succesfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='Churn',
                                       time_features=[])),
                 ('imputer',
                  Iterative_Imputer(add_indicator=False,
                                    classifier=LGBMClassifier(boosting_type='gbdt',
                                                              class_weight=None,
                                                              colsample_bytree=...
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=6071,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False)]],
          verbose=False),
 'LR.pkl')

In [21]:
import pickle

with open('LR.pk', 'wb') as f:
    pickle.dump(best_model, f)

In [22]:
with open('LR.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [23]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [24]:
automl = setup(data = df, target = 'Churn',  fold_shuffle=True, imputation_type='iterative')

IntProgress(value=0, description='Processing: ', max=3)

Initiated  . . . . . . . . . . . . . . . . . .            23:36:03
Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data

Text(value="Following data types have been inferred automatically, if they are correct press enter to continueâ€¦

                             Data Type
tenure                         Numeric
PhoneService               Categorical
Contract                   Categorical
MonthlyCharges                 Numeric
TotalCharges                   Numeric
Tenure_TotalCharges_ratio      Numeric
TotalCharges_Tenure_ratio      Numeric
Churn                            Label

quit

SystemExit: Read the documentation of setup to learn how to overwrite data types over the inferred types. setup function must run again before you continue modeling.

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   tenure                     7032 non-null   int64
 1   PhoneService               7032 non-null   int64
 2   Contract                   7032 non-null   int64
 3   MonthlyCharges             7032 non-null   float64
 4   TotalCharges               7032 non-null   float64
 5   Churn                      7032 non-null   int64
 6   Tenure_TotalCharges_ratio  7032 non-null   float64
 7   TotalCharges_Tenure_ratio  7032 non-null   float64
dtypes: float64(4), int64(4)
memory usage: 752.5+ KB

In [26]:
new_data = df.iloc[-2:-1].copy()
loaded_model.predict(new_data)

array([1])

In [27]:
import pickle

with open('LR.pk', 'wb') as f:
    pickle.dump(best_model, f)

In [28]:
with open('LR.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [29]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [30]:
automl = setup(data = df, target = 'Churn',  fold_shuffle=True, imputation_type='iterative')

In [32]:
new_data = df.iloc[-2:-1].copy()
loaded_model.predict(new_data)

array([1])

In [34]:
loaded_lr = load_model('LR')

Transformation Pipeline and Model Successfully Loaded

In [35]:
predict_model(loaded_lr, new_data)

,tenure,PhoneService,Contract,MonthlyCharges,TotalCharges,Churn,Tenure_TotalCharges_ratio,TotalCharges_Tenure_ratio,Label,Score
customerID,,,,,,,,,,
8361-LTMKD,4,1,1,74.4,306.6,1,0.013046,76.65,1,0.5797

In [36]:
from IPython.display import Code

Code('predict_churn.py')

predict_churn.py

In [37]:
%run predict_churn.py

Exception: File `'predict_churn.py'` not found.

In [38]:
from IPython.display import Code

Code('/Users/thomascurl/Downloads/predict_churn.py')

/Users/thomascurl/Downloads/predict_churn.py

In [39]:
import pandas as pd
from pycaret.classification import predict_model, load_model

def load_data(filepath):
    """
    Loads diabetes data into a DataFrame from a string filepath.
    """
    df = pd.read_csv(filepath, index_col='Patient number')
    return df


def make_predictions(df):
    """
    Uses the pycaret best model to make predictions on data in the df dataframe.
    """
    model = load_model('LDA')
    predictions = predict_model(model, data=df)
    predictions.rename({'Label': 'Diabetes_prediction'}, axis=1, inplace=True)
    predictions['Diabetes_prediction'].replace({1: 'Diabetes', 0: 'No diabetes'},
                                            inplace=True)
    return predictions['Diabetes_prediction']


if __name__ == "__main__":
    df = load_data('data/new_diabetes_data.csv')
    predictions = make_predictions(df)
    print('predictions:')
    print(predictions)

FileNotFoundError: [Errno 2] No such file or directory: 'data/new_diabetes_data.csv'

In [40]:
automl = setup(data = df, target = 'Churn',  preprocess=True, fold_shuffle=True, imputation_type='iterative')

IntProgress(value=0, description='Processing: ', max=3)

Initiated  . . . . . . . . . . . . . . . . . .            23:36:03
Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data

Text(value="Following data types have been inferred automatically, if they are correct press enter to continueâ€¦

                             Data Type
tenure                         Numeric
PhoneService               Categorical
Contract                   Categorical
MonthlyCharges                 Numeric
TotalCharges                   Numeric
Tenure_TotalCharges_ratio      Numeric
TotalCharges_Tenure_ratio      Numeric
Churn                            Label

quit

SystemExit: Read the documentation of setup to learn how to overwrite data types over the inferred types. setup function must run again before you continue modeling.

In [45]:
automl = setup(data = df, target = 'Churn', preprocess=False, fold_shuffle=True, imputation_type='iterative')